### PR TITLE
Feature/enable remove position via keypress

### PR DESCRIPTION
**Pull request by jonpeters**
(Omitting a GIF since it would appear no differently than the default method of deleting an edit handle)

Basically, this is another usability requirement of the Map Maker application.

### CODE REVIEW

**Comment by georgios-uber** [comment]
Seems good.

**Comment by supersonicclay** [comment]
On the surface, this seems a bit too specific to require increasing the API's surface area. Why is this functionality needing to be built into the layer itself as opposed being implementing in the consuming application?

If there's some capability not exposed out of `EditableGeoJsonLayer` to enable this use case, perhaps we should look more closely at that before adding each application's concerns into nebula.

**Comment by georgios-uber** [comment]
Agree with Clay.

**Comment by jonpeters** [comment]
It doesn't have to be in the layer. I figured I'd put it there in case other consuming applications had the same requirement. Let me validate that it works when implemented on the application and then I will back out this PR ...

**Pull request closed without merging**
