### PR TITLE
Typescript migration

### PR DESCRIPTION
**Pull request by kikonejacob**
I created a new PR to take advantage of conversion tooling.
## Strategy
* use Flow to typescript CLI https://github.com/khan/flow-to-ts to automate most of the conversion
* Use of [Typescript ESLINT](https://github.com/typescript-eslint/typescript-eslint) to quickly fix types issues.
* Convert the code to typescript with minimal/no  refactor.
* use Loose typescript rules to allow progressive transition
    * I disabled `typescript strict mode`
   * Use `//@ts-ignore`  to mask types errors
   * Use `any` for unknown types

**This PR does not bring the code to the typescript standard.  My idea was to convert first to typescript and from there, we all can improve the types.**

While converting, a lot of errors, missing imports and export surfaced. I fixed the best I could.

## What is next?
The following tasks can be done to improve code quality
- Converting examples to typescript or remove types from examples.
- Move to a stricter typescript and ESLINT rules
- Replace `geojson-types.ts` by [@types/geojson](https://www.npmjs.com/package/@types/geojson)
## Note
If this PR is merged, please take 10 min to get familiar with [Typescript](https://www.typescriptlang.org)

To create a file that has `jsx` please use `.tsx` extension. For anything else use `.ts`.
I upgraded to prettier 2.0 which seems to now have trailing commas by default.

### CODE REVIEW

**Comment by supersonicclay** [comment]
Wow this is fantastic @kikonejacob ! It'll take a bit to review it. But one thing I noticed out of the gate is that we seem to be getting an error after publishing your branch.

I published this as version `0.18.0-alpha.0` and created a code sandbox:
https://codesandbox.io/s/test-typescript-bm8uy

But I'm getting an error:
```
TypeError
Cannot add property layerName, object is not extensible
    at _defineProperty (https://bm8uy.csb.app/node_modules/
nebula.gl/layers/dist/layers/editable-geojson-layer.js:42:186
    at new EditableGeoJsonLayer (https://bm8uy.csb.app/node_modules/
nebula.gl/layers/dist/layers/editable-geojson-layer.js:224:5
GeometryEditor
/index.js:23:16
  20 | });
  21 | const [selectedFeatureIndexes] = React.useState([]);
  22 | 
> 23 | const layer = new EditableGeoJsonLayer({
     |              ^
  24 |   // id: "geojson-layer",
  25 |   data: features,
```

I can look more into it, but if you have cycles to debug, that'd be great. Thanks again!

**Comment by kikonejacob** [comment]
@supersonicclay  I think

> Wow this is fantastic @kikonejacob ! It'll take a bit to review it. But one thing I noticed out of the gate is that we seem to be getting an error after publishing your branch.
> 
> I published this as version `0.18.0-alpha.0` and created a code sandbox:
> https://codesandbox.io/s/test-typescript-bm8uy
> 
> But I'm getting an error:
> 
> ```
> TypeError
> Cannot add property layerName, object is not extensible
>     at _defineProperty (https://bm8uy.csb.app/node_modules/
> nebula.gl/layers/dist/layers/editable-geojson-layer.js:42:186
>     at new EditableGeoJsonLayer (https://bm8uy.csb.app/node_modules/
> nebula.gl/layers/dist/layers/editable-geojson-layer.js:224:5
> GeometryEditor
> /index.js:23:16
>   20 | });
>   21 | const [selectedFeatureIndexes] = React.useState([]);
>   22 | 
> > 23 | const layer = new EditableGeoJsonLayer({
>      |              ^
>   24 |   // id: "geojson-layer",
>   25 |   data: features,
> ```
> 
> I can look more into it, but if you have cycles to debug, that'd be great. Thanks again!

@supersonicclay  I think the error is now resolved.
How do you test the examples apps? 
Are all examples supposed to work?
How do I test the website app?

**Comment by supersonicclay** [comment]
```
cd nebula.gl
yarn
cd examples/advanced (also try examples/react-map-gl-draw)
yarn
yarn start-local
```

also you can check that `yarn build` from the root folder works

@georgios-uber how can we check the website is still working? I tried running `yarn start` but got errors around cleaning examples.

**Comment by xintongxia** [comment]
> @georgios-uber how can we check the website is still working? I tried running `yarn start` but got errors around cleaning examples.

```
yarn develop
```

**Comment by supersonicclay** [comment]
@kikonejacob: Good news. A simple test of the latest on your branch looks to be working! I published `0.18.0-alpha.1`
https://codesandbox.io/s/test-typescript-bm8uy

**Comment by kikonejacob** [comment]
> > @georgios-uber how can we check the website is still working? I tried running `yarn start` but got errors around cleaning examples.
> 
> ```
> yarn develop
> ```

That did not work.

**Comment by kikonejacob** [comment]
The website is now working locally. I think the PR is ready.

Things that  I noticed and I was curious to know about are:
     Why are the website and examples not managed by lerna & yarn workspace?
     why is there so many different versions of packages in the same repository?
            deck.gl, react, react-dom, ...etc

**Comment by supersonicclay** [comment]
I'm still seeing some errors in Visual Studio Code, and they look to be roughly the same errors that show up by runnning:
```
cd nebula.gl
./node_modules/.bin/tsc --outDir dist
```
They seem to be errors in the tests. So it might be that we're not running babel/typescript compiler when running tests.

Also, it looks like there are some TypeScript errors in the examples also. For example:
```
cd example/advanced
../../node_modules/.bin/tsc --outDir dist
```

Thanks again tremendously for your work on this. It'll be great to have the library switched over!

**Comment by kikonejacob** [comment]
> I'm still seeing some errors in Visual Studio Code, and they look to be roughly the same errors that show up by runnning:
> 
> ```
> cd nebula.gl
> ./node_modules/.bin/tsc --outDir dist
> ```
> 
> They seem to be errors in the tests. So it might be that we're not running babel/typescript compiler when running tests.
> 
> Also, it looks like there are some TypeScript errors in the examples also. For example:
> 
> ```
> cd example/advanced
> ../../node_modules/.bin/tsc --outDir dist
> ```
> 
> Thanks again tremendously for your work on this. It'll be great to have the library switched over!

Type errors are intentionally not corrected for test folders. Babel can run fine without typescript checks for tests.   babel/typescript is just translating. it is not checking for types errors.
I think it is not big since we are progressively moving to typescript and source code types errors are covered.

Also running the following is not the right way to test types
`cd examples/advanced
../../node_modules/.bin/tsc --outDir dist
```
Please use `types-check` script in package.json. It runs `tsc --noEmit`.
you can add it in each package that needs it.

**Comment by kikonejacob** [comment]
in each package that has typescript, I have added tsconfig
```
{
    "extends": "../../tsconfig.json",
    "compilerOptions": {
        "outDir": "dist/",
        "skipLibCheck": true,
        "resolveJsonModule": true
    },
    "exclude": [
        "node_modules",
        "dist"
    ],
    "include": [
        "src", // Please include folders that you want to include in typescript check
    ]
}
```

**Comment by kikonejacob** [comment]
@supersonicclay  I took some time this morning to fix types in test.  
Please use `yarn types-check` to check for types in the project
Also, I added ts-jest to allow type checking in test.

**Comment by supersonicclay** [comment]
Regarding examples, I believe the original intention was to make it so that someone could just copy the folder and run it from outside the nebula repo. But I think it makes more sense to just be another module of lerna. And we can use codesandbox for examples that people can run from outside the nebula repo.

**Comment by supersonicclay** [comment]
Fantastic! Thanks @kikonejacob!

**Pull request merged**
