### PR TITLE
make @danmarshall/deckgl-typings devDependencies

### PR DESCRIPTION
**Pull request by ikeyan**
Fix https://github.com/uber/nebula.gl/issues/526

### CODE REVIEW

**Comment by ikeyan** [comment]
The page says "You have agreed to the CLA for uber/nebula.gl", but even after clicking `recheck` CLAassistant won't recognize it

**Review by ibgreen — APPROVED** [review]

**Review by igorDykhta — APPROVED** [review]

**Comment by Akiyamka** [comment]
Look like it can be closed by #809

**Comment by igorDykhta** [comment]
@Akiyamka we already merged deck 8.8 bump with ts types, @danmarshall/deckgl-typings devDependencies removed as well there

**Comment by Akiyamka** [comment]
Great, in that case it can be closed

**Pull request closed without merging**
