### PR TITLE
react-map-gl-draw: Closing polygon drawing on dblclick

### PR DESCRIPTION
**Pull request by ilyabo**
This PR addresses the issue #330

We did some user testing for polygon drawing and realized that very few users discovered that they have to connect the last and the first points to close a polygon. Double click is a standard way of doing this. Hence, it's very important to support it.

cc @xintongxia

### CODE REVIEW

**Comment by ilyabo** [comment]
The CI build is failing because of the missing `FOSSA_API_KEY`. How can I fix this?

**Comment by georgios-uber** [comment]
> The CI build is failing because of the missing `FOSSA_API_KEY`. How can I fix this?

Seems like the build is broken, just ignore for now, I'm trying to fix.

**Comment by georgios-uber** [comment]
@ilyabo  can you push again? I fixed travis ci.

**Comment by xintongxia** [comment]
thanks for your contribution. The current way that react-map-gl-draw handled closing a polygon was from an internal use case, and I think double click to close a polygon also makes a lot sense.

**Pull request merged**
