### PR TITLE
feat: add tooltip info to circle and linestring mode

### PR DESCRIPTION
**Pull request by chetta8**

### CODE REVIEW

**Comment by supersonicclay** [comment]
Thanks for your contribution @chetta8. After you sign the Contributor License Agreement, I'll be able to merge this.

**Comment by kargeor** [comment]
@chetta8 Please sign CLA. If you have any trouble signing CLA let us know.

**Comment by chetta8** [comment]
Hi, sorry for the late reply, I just signed the CLA.

**Comment by Akiyamka** [comment]
Conflicts resolved. @igorDykhta can we merge it?

**Review by igorDykhta — APPROVED** [review]
Tested it. works as expected.

**Pull request merged**
