### PR TITLE
add billboard prop to editable-geojson-layer

### PR DESCRIPTION
**Pull request by georgios-uber**

### CODE REVIEW

**Comment by amangijoe** [comment]
billboard feature when set to false doesn't work

**Comment by georgios-uber** [comment]
`billboard` is not related to extrusion. It only affects the angle of extrusion.

**Comment by amangijoe** [comment]
thanks @georgios-uber Is there a way that I can disable extrusion or do I have to programmatically ignore elevation value from geojson data?

**Comment by supersonicclay** [comment]
I'd suggest creating a new issue and you can reference this PR in the description

**Pull request merged**
