### PR TITLE
Ability to transform translate (move) any feature

### PR DESCRIPTION
**Pull request by sivako**
Under modify mode with action "transformTranslate" and select any feature.
Mouse pointer down hold and drag to desired direction to move the feature.
transform-translate

### CODE REVIEW

**Comment by supersonicclay** [comment]
Fixes #18

**Comment by supersonicclay** [comment]
I'd like to get #81 landed first then rebase this

**Comment by georgios-uber** [comment]
@supersonicclay I'll wait for #81

**Comment by supersonicclay** [comment]
#81 landed, so you can rebase now

**Comment by sivako** [comment]
Thanks @supersonicclay @georgios-uber. I merged with latest and updated PR.

**Pull request merged**
