### PR TITLE
fix scripts to work crossplatform

### PR DESCRIPTION
**Pull request by vkozio**
fixes for build scripts to work on Windows

### CODE REVIEW

**Comment by ibgreen** [comment]
Thanks for contributing. I have mixed feelings about this change.

While Uber has not yet contributed nebula.gl to the OpenJS foundation, nebula.gl is effectively a key extension frameworks in the bigger deck.gl / vis.gl ecosystem which is under open governance.

As part of that ecosystem, one goal of the maintainers is to work towards a similar structure on repositories and build tools etc, so that maintainers can move with comfort between the repos.

Since very few deck.gl / vis.gl contributors work on Windows, so for Windows development, we have focused on supporting the WSL environment (see e.g. https://loaders.gl/docs/developer-guide/dev-env#environment-setup) rather than trying to use cross-platform tools.

No one among the core contributors can really test and maintain these cross platform tools on Windows, and I don't see us adding such cross platform tooling to other repos, so I worry that having this here won't be helpful to the team long term, as it represents an additional abstraction to learn and maintain.

**Comment by ibgreen** [comment]
@Komzpa Yes, #2 would seem more likely to stay "maintained", as the tooling used on mac / linux should then still work on WSL.  

I'd love to see that loaders.gl Windows developer page moved up into the common [visgl developer-process](https://github.com/visgl/tsc/tree/master/developer-process), at least as a recommendation for the frameworks, but Windows development is not the highest priority for the TSC.

**Comment by ibgreen** [comment]
And yes, we'd definitely accept PRs that fix issues under WSL.

**Comment by ibgreen** [comment]
@Komzpa If your team is planning to stepping up as the core maintainer of nebula.gl, then you would also get to be decision makers in how the repo should be structured, and it would ultimately be your call how to support Windows dev. 

What I am saying is that while I value alignment between the repos, I’d rather have a strong maintainer for nebula.gl, at the cost of some divergence. 

Alternatively: if not merging this makes you less likely to contribute, then that is a good reason to merge it.

**Comment by Akiyamka** [comment]
We have decided that we are not going to measure it yet

**Pull request closed without merging**
