### PR TITLE
Ability to move feature in new cursor mode

### PR DESCRIPTION
**Pull request by sivako**
@georgios-uber @supersonicclay, I have fixed the issues with move feature. 
Adding the new "cursor" mode,  In this mode the feature selections will have bounding box to feature.
With this user can move, duplicate, resize, (may be rotate) etc. (currently this PR will have "move" feature). 

Scenario: Select mode as "cursor" -> Select any feature -> mouse click + hold on feature and drag to move to desired location.

nebula-move-feature-2

### CODE REVIEW

**Comment by georgios-uber** [comment]
I made a gif of how it works, looks like the shape is trying to avoid the mouse.
aaaaa

**Comment by sivako** [comment]
Thanks you @supersonicclay and @georgios-uber.  I could see the issue mentioned and have fixed the issue.  Now the feature follows the mouse on pointer down + drag the feature.  I have move the "cursor" mode to different PR https://github.com/uber/nebula.gl/pull/98.  Can you please check both of these?. Thanks Again.

**Comment by supersonicclay** [comment]
Hmmm. Still no.
translate

**Comment by sivako** [comment]
Based on discussion with @supersonicclay, Will need to update feature scenario and logic behind. Also will raise PR after #96.

**Pull request closed without merging**
