### PR TITLE
Add draw square mode

### PR DESCRIPTION
**Pull request by StijnAmeloot**
Added new edit mode which allows the user to draw square-shaped Polygon features.
It's possible to draw a square by clicking twice or by dragging (dragToDraw set to true).

Demo
draw-square-mode

### CODE REVIEW

**Review by kargeor — COMMENTED** [review]
Can we also merge with the other ones, and accept `modeConfig` ?

@supersonicclay what do you think?

**Comment by StijnAmeloot** [comment]
Personally I think it makes sense to have separate edit modes because the library already has multiple edit modes for different kind of shapes (e.g. circle, ellipse, rectangle,...) and different ways of creating a shape (e.g. draw circle from center, draw ellipse using 3 points,...).
I think it's better to avoid introducing a small inconsistency by requiring to provide the square true/false parameter.
This is my point of view, I'm open to suggestions.

**Review by kargeor — APPROVED** [review]

**Comment by kargeor** [comment]
Can you help resolve conflicts?

**Comment by StijnAmeloot** [comment]
Merged the master branch into this feature branch and resolved the conflicts.

**Review by supersonicclay — APPROVED** [review]

**Comment by supersonicclay** [comment]
Can you resolve conflicts again and I can get this merged?

**Comment by StijnAmeloot** [comment]
> Can you resolve conflicts again and I can get this merged?

Done

**Review by igorDykhta — APPROVED** [review]

**Pull request merged**
